console.log('Welcome first programming Ankit Chaubey');
fullName = "Ankit Chaubey";
console.log(fullName);
age = 24;
console.log("My age is " + age);
y = undefined;
x = null;
console.log(x);
isFollow = false;
console.log(isFollow);